#!/usr/bin/env python3
"""
Task 1 species-scoping pass: cross-reference every detection against the
registry manifest's animal_type, exclude confirmed non-target contamination
(the Pimlico Race Course horse-track false positives, documented in
docs/labeling_guide.md), and produce a final per-species completeness table
across the entire 417-farm registry -- not just the poultry-dominant subset
that's been the focus of validation so far.

Usage:
    python scripts/finalize_task1_species_scope.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "data/raw/naip_tiles_pc_4band_full/manifest.json"
DETECTIONS_PATH = ROOT / "data/processed/detections/full_registry_unet_tulbure_detections.geojson"
OUT_DETECTIONS = ROOT / "data/processed/detections/full_registry_unet_tulbure_detections_task1_scoped.geojson"
OUT_SUMMARY = ROOT / "docs/task1_species_completeness.md"

# Task 1's explicit scope (docs/NEXT_SESSION.md, 2026-09-15): poultry, dairy,
# swine, beef, lagoons. Horses are not a Task 1 target species and Pimlico
# Race Course's 4 detections are a documented, confirmed false-positive class
# (grandstand/stable roofs sharing the poultry-house long-roof shape) --
# see docs/labeling_guide.md. Excluded here, not silently dropped from the
# registry itself.
EXCLUDED_ANIMAL_TYPES = {"horses"}

POULTRY_TYPES = {"chickens_not_laying_hens", "laying_hens_dry_manure", "turkeys", "ducks_liquid_manure"}
DAIRY_TYPES = {"dairy_cattle"}
BEEF_TYPES = {"cattle_includes_heifers"}
SWINE_TYPES = {"swine_55_lbs"}


def species_group(animal_type: str) -> str:
    if animal_type in POULTRY_TYPES:
        return "poultry"
    if animal_type in DAIRY_TYPES:
        return "dairy"
    if animal_type in BEEF_TYPES:
        return "beef"
    if animal_type in SWINE_TYPES:
        return "swine"
    if animal_type in EXCLUDED_ANIMAL_TYPES:
        return "excluded (not a Task 1 target)"
    return "unknown (registry data gap)"


def main():
    manifest = json.loads(MANIFEST_PATH.read_text())
    farm_type = {f["farm_name"]: f["animal_type"] for f in manifest}

    det = json.loads(DETECTIONS_PATH.read_text())
    excluded_farms = {f["farm_name"] for f in manifest if f["animal_type"] in EXCLUDED_ANIMAL_TYPES}

    kept_features = [
        feat for feat in det["features"]
        if feat["properties"]["farm_name"] not in excluded_farms
    ]
    n_removed = len(det["features"]) - len(kept_features)

    OUT_DETECTIONS.write_text(json.dumps({"type": "FeatureCollection", "features": kept_features}, indent=2))
    print(f"Removed {n_removed} detections from {len(excluded_farms)} excluded (non-Task-1-target) farm(s).")
    print(f"Wrote {OUT_DETECTIONS} ({len(kept_features)} detections)")

    det_counts = {}
    for feat in kept_features:
        fn = feat["properties"]["farm_name"]
        det_counts[fn] = det_counts.get(fn, 0) + 1

    groups = {}
    for f in manifest:
        g = species_group(f["animal_type"])
        groups.setdefault(g, []).append(f)

    lines = ["# Task 1 species completeness (2026-09-21)\n",
             "Cross-references every farm in the 417-farm active registry against",
             "current detections, grouped by Task 1's actual target species.",
             "Generated by `scripts/finalize_task1_species_scope.py`.\n"]

    for group_name in ["poultry", "dairy", "beef", "swine", "unknown (registry data gap)", "excluded (not a Task 1 target)"]:
        farms = groups.get(group_name, [])
        if not farms:
            continue
        n_with_det = sum(1 for f in farms if det_counts.get(f["farm_name"], 0) > 0)
        lines.append(f"\n## {group_name} ({len(farms)} farms, {n_with_det}/{len(farms)} with >=1 detection)\n")
        lines.append("| Farm | animal_type | headcount | detections |")
        lines.append("|---|---|---|---|")
        for f in sorted(farms, key=lambda x: -det_counts.get(x["farm_name"], 0)):
            n = det_counts.get(f["farm_name"], 0)
            lines.append(f"| {f['farm_name']} | {f['animal_type']} | {f['headcount']} | {n} |")

    OUT_SUMMARY.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_SUMMARY}")


if __name__ == "__main__":
    main()
